in_season/in_season/urls.py
"""in_season URL Configuration """

from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('static_site.urls')),
]

in_season/static_site/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'static_site'

urlpatterns = [
    
    path('', views.index, name='home'),
    path('contact/', views.contact, name='contact'),
    path('shop/', views.shop, name='shop'),
    path('shop/<str:category>', views.shop, name='shop'),
    path('shop/product/<str:product_name>', views.single, name='single_product'),
    path('shop/product/<str:product_name>/<str:edit>', views.single, name='single_product_edit'),
    path('shop/basket/', views.basket, name='my_basket'),
    path('shop/basket/<str:product_name>/<str:key>', views.basket, name='delete'),
    path('shop/checkout/', views.checkout, name='checkout'),
# Account settings/pages 
    path('accounts/login/', auth_views.LoginView.as_view(template_name='static_site/login.html'), name='login'),
    path('accounts/register/', views.register_user, name='register'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='static_site:home'), name='logout'),
    path('accounts/switch/', auth_views.logout_then_login, name='switch_user'),
# Static pages
    path('<str:page>/', views.static_pages, name='static'),
    path('site/test', views.test_page, name='test'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

in_season/static_site/models.py
from django.db import models
from decimal import Decimal
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Unit(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=25)
    abbreviation = models.CharField(max_length=25)

    def __str__(self):
        return self.abbreviation


class Product(models.Model):
    name = models.CharField(max_length=25)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, null=True)
    current_price = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))
    old_price = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    market_price = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))
    image = models.ImageField(upload_to='products/%Y.%m', blank=True, null=True)
    is_available = models.BooleanField(default=False)

    class Meta:
        ordering=['-id']
    
    def __str__(self):
        return self.name

    def discount(self):
        discount = self.market_price - self.current_price
        return 0 if discount < 0 else discount

    def percentage_discount(self):
        return round(self.discount()/self.current_price * 100)


class Variety(models.Model):
    name = models.CharField(max_length=25, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="variety")

    def __str__(self):
        return self.name


class Stock(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name="in_stock")
    variety = models.ForeignKey(Variety, on_delete=models.SET_NULL, blank=True, null=True)
    details = models.CharField(max_length=120, default='Small')
    quantity = models.IntegerField(default=0)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ['product','variety','details']

    def __str__(self):
        return f'{self.product}_{self.details}'

    def save(self, *args, **kwargs):
        if self.quantity > 0 and self.product.is_available == False: 
            self.product.is_available = True
            self.product.save()
        super().save(*args, **kwargs)


class Phone_Number(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="phone_number")
    number = models.IntegerField()

    def __str__(self):
        return str(self.number)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=400, blank=True, null=True)

    def __str__(self):
        return self.user.username


ORDER_STATUS_CHOICES = (
    ('Pending', 'Pending'),
    ('Placed', 'Placed'),
    ('Dispatched', 'Dispatched'),
    ('In transit', 'In transit'),
    ('Delivered', 'Delivered'),
    ('Cancelled', 'Cancelled'),
)

class Order(models.Model):
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    addressee = models.CharField(max_length=350)
    contact = models.ForeignKey(Phone_Number, null=True, on_delete=models.SET_NULL)
    location = models.CharField(max_length=400, blank=True, null=True)
    status = models.CharField(max_length=120, default='Pending', choices=ORDER_STATUS_CHOICES)
    is_ordered = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_placed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.customer}_{self.status}'


    def get_order_items(self):
        return self.products.all()
    
    def get_total(self, total=0, deal=0):
        items = {}
        products = self.get_order_items()
        for order_item in products:
            product_total = order_item.get_total()
            product = order_item.product
            if order_item.product in items.keys():
                items[product].update({order_item:order_item.quantity})
            else:
                items.update({product: {order_item:order_item.quantity}})
            total += product_total
            if product.discount(): deal += product.discount()
        return items, total, deal


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    details = models.CharField(max_length=120, default='Small')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return f'{str(self.product).lower()}_{self.details}'

    def get_total(self):
        return self.product.current_price * self.quantity

    def check_for_deal(self):
        return 0 if self.product.discount < 0 else self.product.discount

in_season/static_site/forms.py
from django import forms

COUNTY_CHOICES = [('Nairobi', 'Nairobi')]

class CheckoutForm(forms.Form):
    first_name = forms.CharField(label="First Name*", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label="Last Name (Optional)", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    county = forms.ChoiceField(label="County*", widget=forms.Select(attrs={'class': 'form-control'}), choices=COUNTY_CHOICES)
    delivery_route = forms.CharField(label="Delivery Route*", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Estate / Local Area Name'}))
    street_address = forms.CharField(label="Street Address*", max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Landmark'}))
    additional_description = forms.CharField(label="Additional Description (Optional)", max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'eg. Name of shop or Opposite Naivas supermarket'}))
    phone_number = forms.IntegerField(label="Phone Number*", widget=forms.NumberInput(attrs={'class': 'form-control'}))

in_season/static_site/views.py
import json
import base64
from datetime import datetime
from decimal import *
from django.http import Http404
from .forms import CheckoutForm
from django.contrib.auth.models import User
from .logged_user_functions import complete_order
from .models import Category, Product, Phone_Number, Stock
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .static_helper_functions import get_json_respose, paginate, get_context
from .helper_functions import add_to_basket, remove_from_basket, get_total_cost, clear_basket, edit_basket_item, add_all_orders_to_db


import requests
from requests.auth import HTTPBasicAuth



DEAL_OF_THE_DAY = 'avocado'
DISCOUNT = Decimal('3.00')

def index(request):
    products = Product.objects.all()[:4]
    deal = get_object_or_404(Product, name__iexact=DEAL_OF_THE_DAY)
    context = get_context(request, 'home', products)
    context.update({'deal': deal})
    return render(request, 'static_site/index.html', context)

def test_page(request):
    context = get_context(request, 'home')
    return render(request, 'static_site/test.html', context)

#static pages
def static_pages(request, page):
    context = get_context(request, 'home')
    if page == 'terms-and-conditions': return render(request, 'static_site/terms.html', context)
    elif page == 'privacy-policy': return render(request, 'static_site/privacy_policy.html', context)
    elif page == 'FAQs': return render(request, 'static_site/faqs.html', context)
    else : return redirect('static_site:home')


def contact(request):
    context = get_context(request, 'contact')
    return render(request, 'static_site/contact.html', context)


def shop(request, category=''):
    #if category is provided, perform filter, else grab all products
    if category:
        category = category[:-1]
        categ_object = Category.objects.filter(name__iexact=category)[0]
        products = categ_object.product_set.all() #all products contained in this category

        #if request is ajax, return filtered products as a json object
        if request.is_ajax(): return get_json_respose(products)            
    else:
        products = Product.objects.all()
    categs = Category.objects.all() #all categories
    products = paginate(request, products)
    context = get_context(request, 'shop', products)
    context.update({'categs': categs, 'filtr': category})
    return render(request, 'static_site/shop.html', context)


def single(request, product_name, edit=""):
    product = get_object_or_404(Product,name__iexact=product_name)    
    if request.method == "POST":
        if request.POST.get('key'):
        # If a key has been passed then it is an edit request
            product_key = request.POST.get('key')
            edit_basket_item(request, product_name, product_key)
            return redirect('static_site:my_basket')
        # If there is no key, then simply add item to basket
        else: 
            add_to_basket(request, product_name) 
    
    related_products = Product.objects.filter(category=product.category).exclude(id=product.id)
    context = get_context(request, 'single', related_products)
    context.update({'product': product, "edit": edit})
    return render(request, 'static_site/single_product.html', context)


def basket(request, product_name="", key=""):
    if product_name and key:
        remove_from_basket(request, product_name, key)        
        return redirect('static_site:my_basket')
    products, subtotal, deal, total = get_total_cost(request, DEAL_OF_THE_DAY, DISCOUNT)
    context = get_context(request, 'basket', products)
    context.update({'total': total, 'deal': deal, 'subtotal': subtotal})
    return render(request, 'static_site/my_basket.html', context)


@login_required()
def checkout(request):
    if request.method == 'POST':
        #validate input and adding to variables
        form = CheckoutForm(request.POST)
        if form.is_valid():
            if request.POST.get('payment') == 'Pay now': process_payment(request)
            complete_order(request, form)
            clear_basket(request)
    else:
        form = CheckoutForm()    
    order_items = add_all_orders_to_db(request)
    products, subtotal, deal, total = get_total_cost(request, DEAL_OF_THE_DAY, DISCOUNT)
    #if any product order was placed, redirect to shop else, go to checkout
    if not products: return redirect('static_site:shop')
    #create order item object list for all the orders stored in session data            
    context = get_context(request, 'checkout', products)
    context.update({'total': total, 'deal': deal, 'subtotal': subtotal, 'form':form})
    return render(request, 'static_site/checkout.html', context)


def register_user(request):
    if request.method == 'POST':
        username = request.POST.get('username') if request.POST.get('username') else ''
        password = request.POST.get('password') if request.POST.get('password') else ''
        email = request.POST.get('email') if request.POST.get('email') else ''
        phone_number = request.POST.get('phone') if request.POST.get('phone') else ''
        if username and password:
            user = User.objects.create_user(username, password=password)
            if phone_number:
                phone_number = Phone_Number.objects.create(user=user, number=phone_number)                
            if email: 
                user.email = email
            user.save()
            login(request, user)
    return redirect('static_site:checkout')


def process_payment(request):
    # Authenticate, i.e. get access token
    access_token = get_mpesa_auth()
    credentials_expiry = '2020-05-10T11:10:03+03:00'
    short_code = '174379'
    timestamp = get_timestamp()
    lnm_passkey = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
    password = encode_password(short_code, lnm_passkey, timestamp)
    transaction_type = ['CustomerPayBillOnline', 'CustomerBuyGoodsOnline']
    amount = request.POST.get('pay_amount')    
    phone_number = '254708374149'
    callback_url = ''
    account_ref = ''
    description = ''
    
    headers = { f'Authorization": "Bearer {access_token}'}

    request = {
        "BusinessShortCode": f"{short_code}",
        "password": f"{password}",
        "Timestamp": f"{timestamp}",
        "TransactionType": f"{transaction_type}",
        "Amount": f'{amount}',
        "PartyA": f"{phone_number}",
        "PartyB": f"{short_code}",
        "PhoneNumber": f"{phone_number}",
        "CallBackURL": f"{callback_url}",
        "AccountReference": f"{account_ref}",
        "TransactionDesc": f"{description}"
    }

    api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
  
    response = requests.post(api_url, json = request, headers=headers)
    print (response.text)


def get_timestamp():
    now = datetime.now()
    now = f'{now.strftime("%Y%m%d%H%M%S")}' #YYMMDDHHmmss (Time is 24hr-based)
    return now

def encode_password(shortcode, lnm_passkey, timestamp):
    password = f'{shortcode}{lnm_passkey}{timestamp}'
    password_in_bytes = password.encode('ascii')
    password = base64.b64encode(password_in_bytes)
    return password

def get_mpesa_auth():
    consumer_key = "pcj9rupHg2LUpiPUtT5AEMhTTn3y40de"
    consumer_secret = "7MwTgzhgZivUz9A4"
    api_URL = "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
    json_data = requests.get(api_URL, auth=(consumer_key, consumer_secret))
    json_data = json.loads(json_data.text)  # Converts returned json object into a python dictionary object
    access_token = json_data.get("access_token")
    print(access_token)
    return access_token

in_season/static_site/templates/static_site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-------------------------------------HEADER---------------------------------------------------->

<head>
    <title>In Season!- Order your stock today</title>
    <link rel="shortcut icon" href="{% static 'static_site/images/logo_deep.png'%}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-------------------------------------FONTS------------------------------------------------->
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <!-------------------------------------CSS------------------------------------------------->
    <link rel="stylesheet" href="{% static 'static_site/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'static_site/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'static_site/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'static_site/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'static_site/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'static_site/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'static_site/css/style.css' %}">
</head>

<!-------------------------------------BODY------------------------------------------------------->

<body class="goto-here">
    <div class="py-1 bg-primary">
        <div class="container">
            <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
                <div class="col-lg-12 d-block">
                    <div class="row d-flex mx-auto">
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
                            <span class="text">+ 254 735 235598</span>
                        </div>
                        <div class="col-md pr-4 d-flex topper align-items-center">
                            <div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
                            <span class="text">info@inseason.com</span>
                        </div>
                        <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
                            <span class="text">Next-day delivery on orders made from MONDAY - FRIDAY</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'static_site:home'%}">
                <img src="{% static 'static_site/images/logo_deep.png' %}" width="32" height="32" alt="logo"> in Season!
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% if nbar == 'home' %}active{% endif %}"><a href="{% url 'static_site:home'%}" class="nav-link">Home</a></li>
                    {% if nbar == 'home'%}
                    <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                    {% endif %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if nbar == 'shop' or nbar == 'product' or nbar == 'basket' or nbar == 'checkout' %}active{% endif %}" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown04">
                            <a class="dropdown-item {% if nbar == 'shop' or nbar == 'single' %}active{% endif %}" href="{% url 'static_site:shop'%}">Shop</a>
                            <a class="dropdown-item {% if nbar == 'basket' %}active{% endif %}" href="{% url 'static_site:my_basket' %}">My Basket</a> {% if capacity %}
                            <a class="dropdown-item {% if nbar == 'checkout' %}active{% endif %}" href="{% url 'static_site:checkout' %}">Checkout</a> {% endif %}
                        </div>
                    </li>
                    <li class="nav-item {% if nbar == 'contact' %}active{% endif %}"><a href="{% url 'static_site:contact' %}" class="nav-link">Contact</a></li>
                    <li class="nav-item dropdown {% if user.is_authenticated %}cta{% endif %} cta-colored">
                        <a class="nav-link dropdown-toggle" id="dropdownUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="icon-user"></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownUser">
                            <a class="dropdown-item {% if user.is_authenticated %}btn-link disabled{% endif %}" href="{% url 'static_site:register' %}">Log in</a> {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'static_site:logout' %}">Log out</a>
                            <a class="dropdown-item" href="#">My account</a>
                            <a class="dropdown-item" href="{% url 'static_site:switch_user' %}">Switch account</a> {% endif %}
                        </div>
                    </li>
                    <li class="nav-item cta cta-colored"><a href="{% url 'static_site:my_basket' %}" class="nav-link">
                        <span class="icon-shopping_cart"></span><span class="badge badge-dark">{{capacity}}</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- END nav -->
    
    {% block content %}
    <!-------------------------------ACTUAL BODY CONTENT GOES HERE-------------------------------->
    {% endblock %}

    <!-------------------------------------FOOTER------------------------------------------------->
    <footer class="ftco-footer ftco-section bg-light">
        <div class="container">
            <div class="row">
                <div class="mouse">
                    <a href="#" class="mouse-icon">
                        <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                    </a>
                </div>
            </div>
            <div class="row mb-5">
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">In Season</h2>
                        <p>Reliable, quality, quantity and unmatched support. Focus on growing your business, we'll get you the product.</p>
                        <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4 ml-md-5">
                        <h2 class="ftco-heading-2">Menu</h2>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'static_site:shop'%}" class="py-2 d-block">Shop</a></li>
                            <li><a href="#" class="py-2 d-block">About</a></li>
                            <li><a href="{% url 'static_site:contact'%}" class="py-2 d-block">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Help</h2>
                        <div class="d-flex">
                            <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                                <li><a href="#" class="py-2 d-block">FAQs</a></li>
                                <li><a href="#" class="py-2 d-block">Route Information</a></li>
                                <li><a href="{% url 'static_site:static' 'terms-and-conditions' %}" class="py-2 d-block">Terms &amp; Conditions</a></li>
                                <li><a href="{% url 'static_site:static' 'privacy-policy' %}" class="py-2 d-block">Privacy Policy</a></li>
                                <li><a href="{% url 'static_site:contact'%}" class="py-2 d-block">Contact</a></li>
                            </ul>

                        </div>
                    </div>
                </div>
                <div class="col-md">
                    <div class="ftco-footer-widget mb-4">
                        <h2 class="ftco-heading-2">Have Questions?</h2>
                        <div class="block-23 mb-3">
                            <ul>
                                <li><span class="icon icon-map-marker pb-3"></span><span class="text">Mombasa Road,
                                            Nairobi</span></li>
                                <li><span class="icon icon-phone pb-3"></span><span class="text">+254 739
                                            392</span></a>
                                </li>
                                <li><span class="icon icon-envelope pb-3"></span><span class="text">info@inseason.com</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p id="copyright-area">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | Made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://github.com/Ess-Bidali" target="_blank">Ess_Bidali</a>, frontend tools sourced from <a href="https://colorlib.com"
                            target="_blank">Colorlib themes</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
                <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
                <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                    stroke="#F96D00" /></svg></div>

    <!-------------------------------------JAVASCRIPT------------------------------------------------>
    <script src="{% static 'static_site/js/jquery.min.js' %}"></script>
    <script src="{% static 'static_site/js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'static_site/js/popper.min.js' %}"></script>
    <script src="{% static 'static_site/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'static_site/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'static_site/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'static_site/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'static_site/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'static_site/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'static_site/js/aos.js' %}"></script>
    <script src="{% static 'static_site/js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'static_site/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'static_site/js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'static_site/js/google-map.js' %}"></script>
    <script src="{% static 'static_site/js/main.js' %}"></script>

</body>

</html>

in_season/static_site/templates/static_site/hero_wrap.html
{% load static %}
<div class="hero-wrap hero-bread" style="background-image: url('/static/static_site/images/bg_2a.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="{% url 'static_site:home' %}">Home</a></span>
                    {% if nbar == 'single' or nbar == 'basket' or nbar == 'checkout' %}                        
                    <span class="mr-2"><a href="{% url 'static_site:shop' %}">Shop</a></span>
                        {% if nbar == 'single' or nbar == 'checkout' %}
                        <span class="mr-2"><a href="{% url 'static_site:my_basket' %}">My Basket</a></span>
                        {% endif %}
                    {% endif %}
                </p>
                {% if nbar == 'shop' %}
                <h1 class="mb-0 bread">Products</h1>
                {% elif nbar == 'single'%}
                <h1 class="mb-0 bread">Single Product</h1>
                {% elif nbar == 'basket'%}
                <h1 class="mb-0 bread">My Basket</h1>
                {% elif nbar == 'checkout' %}
                <h1 class="mb-0 bread">Checkout</h1>
                {% elif nbar == 'contact' %}
                <h1 class="mb-0 bread">Contacts</h1>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- {% if alert %} -->
<!-- <section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
        <div class="alert alert-dark bg-dark text-white w-75 alert-dismissible fade show" role="alert">
            <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="close text-white" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>        
    </div>
</section> -->
<!-- {% endif %} -->